datasets:
  flickr_CaptionToPhrase:
    data_type: images
    build_info:
      image_path: /media/train_data/Filteredflickr-30k/images
      ann_path: /media/train_data/Filteredflickr-30k/captiontobbox.json
