datasets:
  invrefcocog:
    data_type: images
    build_info:
      image_path: /media/train_data/coco/coco_images/train/
      ann_path: /media/train_data/RefCOCOg/
      dataset: invrefcocog
      splitBy: umd